core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | 𝙰|𝙵</title>        
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet"> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">  
        
        
        
    </head>

    <body class="bg-fixed" style="background-image: url('https://t4.ftcdn.net/jpg/02/10/62/63/240_F_210626304_asFbznBXrt7ZR9TuxdH7KocnM5JeCg6c.jpg');">
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            
            <a href="/" class="text-[32px] text-[#222222] font-semibold font-semibold">𝙰|𝙵 ArtFolio</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg text-gray-500 font-semibold hover:text-gray-900 hover:text-xl transition-size duration-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg text-gray-500 font-semibold hover:text-gray-900 hover:text-xl transition-size duration-500">Browse</a>
                <a href="https://deepanshu112.github.io/-d-virtual-gallary/" class="text-lg text-gray-500 font-semibold hover:text-gray-900 hover:text-xl transition-size duration-500">Virtual Art gallery</a>

                

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-[#222222] text-white rounded-xl hover:bg-[#383838] transition-colors duration-500">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg text-[#222222] font-semibold bg-[#E9E9E9] border border-[#222222] rounded-xl hover:bg-[#222222] hover:text-[#E9E9E9] transition-colors duration-500">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-[#222222] text-white rounded-xl hover:bg-[#383838] transition-colors duration-500">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 border border-[#222222] text-lg text-[#222222] font-semibold bg-[#E9E9E9] rounded-xl hover:bg-[#222222] hover:text-[#E9E9E9] transition-colors duration-500">Log in</a>
                {% endif %}
            </div>
          </nav>
    


        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between rounded-lg ">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-[#222222] text-[5vh]">About</h3>

                <p class="text-lg text-[#222222]">Welcome to ArtFolio, your online destination for exploring and collecting captivating artworks worldwide. Discover diverse styles, connect with artists, and immerse yourself in virtual exhibitions that bring art to life. Whether you're a seasoned collector or a passionate enthusiast, ArtFolio offers a dynamic platform to discover, appreciate, and acquire art from the comfort of your own home. Join our vibrant community and experience the future of art appreciation today.</p>

            </div>
            <div class="h-[30vh] w-[1px] bg-gray-600 rounded-lg mr-[5vw]"></div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-[#010101] text-[5vh]">Contact Us</h3>
                <div class="border border-[#010101] rounded-lg w-[20vw]">
                    <p class="m-2">No.123, NIET GREATER NOIDA</p>
                    <p class="m-2">7579232738</p>
                    <p class="m-2">Codenova@gmail.com</p>
                </div>

                <ul class="space-y-2 flex gap-10 mt-[9vh]">
                    <li><a href="#" class="text-lg text-[#222222] hover:text-[#010101]">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-[#222222] hover:text-[#010101]">Contact</a></li>
                    <li><a href="#" class="text-lg text-[#222222] hover:text-[#010101]">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-[#222222] hover:text-[#010101]">Term of use</a></li>
                </ul>
            </div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>

    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    

    <div class="text-[13vh] ml-[2vw] uppercase font-semibold flex justify-center items-center ">
        Art Comes Alive here 
    </div>

    <div class=" h-[65vh]">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
            <div class="carousel-item active h-[65vh] object-cover">
              <img src="https://plus.unsplash.com/premium_photo-1664438942574-e56510dc5ce5?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item h-[65vh]">
              <img src="https://arts.mojarto.com/productImages/MA340495/primary/1200/MA340495.jpeg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item h-[65vh]">
              <img src="https://images.unsplash.com/photo-1567061698906-fc74288ce52a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block w-100" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>

    </div> 

        <div class="mt-6 px-6 py-12 rounded-xl">

        <h2 class="mb-24 text-6xl text-center font-semibold uppercase">Newest items</h2>

        <div class="grid grid-cols-4 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="relative rounded-2xl">
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                            <span class="absolute bottom-[50%] right-[25%] text-[#fff] text-5xl font-semibold opacity-70 p-1">ArtFolio</span>
                            <div class="p-6 bg-[#222222] rounded-lg opacity-60 absolute bottom-0 right-0 text-white w-[100%]">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-white">Price: {{ item.price }}</p>
                            </div>
                        </div>                        
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>



    <div class="mt-6 px-6 py-12 bg-[#222222] rounded-xl opacity-90">
        <h2 class="mb-24 text-white text-6xl text-center font-semibold uppercase">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}">
                        <div class="p-6 bg-[#383838] rounded-b-xl">
                            <h2 class="text-xl text-white">{{ category.name }}</h2>
                            <p class="text-white">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
   

    <div class="relative w-[50vw] mx-auto bg-[#222222] rounded-2xl backdrop-filter backdrop-blur-md border-2 border-white shadow-lg py-10 px-7"> 
    <form method="post" action=".">
        {% csrf_token %}


        <h1 class="text-white text-center text-2xl font-semibold mb-8l">Log in</h1>

        <div>
            <div class="mb-3">
                <label class="text-white text-lg font-semibold">Username</label><br>
                {{ form.username }}
            </div>
    
            <div class="mb-3">
                <label class="text-white text-lg font-semibold mt-4">Password</label><br>
                {{ form.password }}
            </div>
    
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
    
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
    
            <button class="w-full bg-white text-gray-900 text-lg font-semibold rounded-md py-3 mt-8 ">Submit</button>

        </div>


        
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="relative w-[50vw] mx-auto bg-[#222222] rounded-2xl backdrop-filter backdrop-blur-md border-2 border-white shadow-lg py-10 px-7">
    <h1 class="text-white text-center text-2xl font-semibold mb-8l">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="text-white text-lg font-semibold">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="text-white text-lg font-semibold mt-4">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="text-white text-lg font-semibold mt-4">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="text-white text-lg font-semibold mt-4">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="w-full bg-white text-gray-900 text-lg font-semibold rounded-md py-3 mt-8 rounded-xl text-[#222222]">Submit</button>
    </form>
</div>
{% endblock %}